apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: step-eks-cluster
  region: ap-south-1

vpc:
  id: "vpc-09241d3b58639130c"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      ap-south-1c: { id: subnet-094c6e7ef7e2308e3 }
      ap-south-1a: { id: subnet-0af6f49fa7a735037 }
      ap-south-1b: { id: subnet-0e905059eb2ad053e }

managedNodeGroups:
  - name: ng-db
    instanceType: t3.small
    labels: { role: builders }
    minSize: 2
    maxSize: 4
    tags:
      Name: ng-db
  - name: ng-spot
    instanceType: t3.medium
    labels: { role: builders }
    minSize: 3
    maxSize: 6
    spot: true
    tags:
      Name: ng-spot
