apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: step-eks-cluster
  region: ap-south-1

vpc:
  id: "vpc-0bb9884f025057768"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      ap-south-1c: { id: subnet-0ff1adde932e82be1 }
      ap-south-1a: { id: subnet-04f69e30e8914d21e }
      ap-south-1b: { id: subnet-0b0bb06c4d660644b }

managedNodeGroups:
  - name: ng-db
    instanceType: t3.small
    labels: { role: builders }
    minSize: 2
    maxSize: 4
    tags:
      Name: ng-db
  - name: ng-spot
    instanceType: t3.medium
    labels: { role: builders }
    minSize: 3
    maxSize: 6
    spot: true
    tags:
      Name: ng-spot
